# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LOGIN(object):
    def setupUi(self, LOGIN):
        LOGIN.setObjectName("LOGIN")
        LOGIN.resize(377, 252)
        self.centralwidget = QtWidgets.QWidget(LOGIN)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logowanie = QtWidgets.QFrame(self.centralwidget)
        self.logowanie.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logowanie.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logowanie.setObjectName("logowanie")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.logowanie)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.logowanie)
        self.label_3.setMouseTracking(True)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.splitter = QtWidgets.QSplitter(self.logowanie)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.input_login = QtWidgets.QLineEdit(self.splitter)
        self.input_login.setStatusTip("")
        self.input_login.setWhatsThis("")
        self.input_login.setText("")
        self.input_login.setPlaceholderText("")
        self.input_login.setObjectName("input_login")
        self.verticalLayout_2.addWidget(self.splitter)
        self.splitter_2 = QtWidgets.QSplitter(self.logowanie)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.input_passwd = QtWidgets.QLineEdit(self.splitter_2)
        self.input_passwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_passwd.setObjectName("input_passwd")
        self.verticalLayout_2.addWidget(self.splitter_2)
        self.splitter_3 = QtWidgets.QSplitter(self.logowanie)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.pushButton = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.splitter_3)
        self.verticalLayout.addWidget(self.logowanie)
        LOGIN.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LOGIN)
        self.statusbar.setObjectName("statusbar")
        LOGIN.setStatusBar(self.statusbar)

        self.retranslateUi(LOGIN)
        self.input_passwd.returnPressed.connect(self.pushButton.click)
        self.input_login.returnPressed.connect(self.input_passwd.setFocus)
        self.pushButton.clicked.connect(self.statusbar.clearMessage)
        QtCore.QMetaObject.connectSlotsByName(LOGIN)

    def retranslateUi(self, LOGIN):
        _translate = QtCore.QCoreApplication.translate
        LOGIN.setWindowTitle(_translate("LOGIN", "dodaj użytkownika"))
        self.label_3.setText(_translate("LOGIN", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">LOGOWANIE</span></p></body></html>"))
        self.label.setText(_translate("LOGIN", "LOGIN:"))
        self.label_2.setText(_translate("LOGIN", "HASŁO:"))
        self.pushButton.setText(_translate("LOGIN", "ZALOGUJ"))
