# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'moduly.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(236, 204)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setLineWidth(5)
        self.label.setMidLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.order = QtWidgets.QPushButton(self.centralwidget)
        self.order.setObjectName("order")
        self.verticalLayout.addWidget(self.order)
        self.delivery = QtWidgets.QPushButton(self.centralwidget)
        self.delivery.setObjectName("delivery")
        self.verticalLayout.addWidget(self.delivery)
        self.users = QtWidgets.QPushButton(self.centralwidget)
        self.users.setObjectName("users")
        self.verticalLayout.addWidget(self.users)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MODUŁY"))
        self.label.setText(_translate("MainWindow", "LISTA MODUŁÓW"))
        self.order.setText(_translate("MainWindow", "ZAMÓWIENIA"))
        self.delivery.setText(_translate("MainWindow", "DOSTAWY"))
        self.users.setText(_translate("MainWindow", "UŻYTKOWNICY"))
